apiVersion: v1
kind: ConfigMap
immutable: false
metadata:
  name: booking
  namespace: apollo11
data:
  PSQL_DB: "apollo11"
  PSQL_HOST: "bookingdb-0.bookingdb.apollo11.svc.cluster.local"
  MOVIE_HOST: "movie.apollo11.svc.cluster.local"
  THEATRE_HOST: "theatre.apollo11.svc.cluster.local"
  MOVIE_PING_PATH: "/ping"
  THEATRE_PING_PATH: "/ping"
  DEBUG_LEVEL: "true"