apiVersion: v1
kind: Service
metadata:
  name: core-api
  labels:
    {{- include "apollo11.labels" . | nindent 4 }}
    app: core-api
spec:
  type: {{ .Values.coreApi.service.type }}
  ports:
    - port: {{ .Values.coreApi.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: core-api
