apiVersion: v1
kind: Service
metadata:
  name: quiz-service
  labels:
    {{- include "apollo11.labels" . | nindent 4 }}
    app: quiz-service
spec:
  type: {{ .Values.quizService.service.type }}
  ports:
    - port: {{ .Values.quizService.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: quiz-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-service
  labels:
    {{- include "apollo11.labels" . | nindent 4 }}
    app: quiz-service
spec:
  replicas: {{ .Values.quizService.replicaCount }}
  selector:
    matchLabels:
      app: quiz-service
  template:
    metadata:
      labels:
        app: quiz-service
    spec:
      containers:
        - name: quiz-service
          image: "{{ .Values.quizService.image.repository }}:{{ .Values.quizService.image.tag }}"
          imagePullPolicy: {{ .Values.quizService.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: {{ .Values.global.databaseUrl | quote }}
