apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apollo11
  name: quiz-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-service
  template:
    metadata:
      labels:
        app: quiz-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: quiz-service
          image: ghcr.io/darshan-raul/apollo11-devsecops/quiz-service:main-900ddaf
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@postgres:5432/apollo11"
  
