apiVersion: batch/v1
kind: CronJob
metadata:
  name: report-generator
spec:
  schedule: "0 6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: ghcr-secret
          containers:
          - name: report-generator
            image: ghcr.io/darshan-raul/apollo11-devsecops/report-generator:main-900ddaf
            imagePullPolicy: IfNotPresent
            env:
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@postgres:5432/apollo11"
          restartPolicy: OnFailure
