apiVersion: v1
kind: ConfigMap
metadata:
  name: core-api-config
  labels:
    app: core-api
data:
  DATABASE_URL: "postgresql://postgres-0.postgres.default.svc.cluster.local:5432/apollo11"
  KEYCLOAK_URL: "http://keycloak.default.svc.cluster.local:8080"
  QUIZ_SERVICE_URL: "http://quiz.default.svc.cluster.local:8080"
  REALM: "apollo11"
  CLIENT_ID: "apollo11-portal"
