global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "node_exporters"
    static_configs:
      - targets:
          - "192.168.1.199:9100"
          - "192.168.1.200:9100"

