[project]
name = "simulator"
version = "0.1.0"
description = "Apollo 11 Simulator"
dependencies = [
    "redis>=5.0.0",
]
requires-python = ">=3.9"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
